IF NOT EXISTS (SELECT * FROM sys.databases WHERE [name] = 'HospitalDB')
BEGIN
	CREATE DATABASE HospitalDB;
END
GO

USE HospitalDB;
GO

-- CREATE FIELD
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE [name] = 'Field' and xtype = 'U')
BEGIN
	CREATE TABLE Field (
		Id INT NOT NULL,
		[Name] VARCHAR(50) NOT NULL,
		CONSTRAINT PKField PRIMARY KEY CLUSTERED (Id)
	)
END
GO

-- CREATE DOCTOR
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE [name] = 'Doctor' AND xtype = 'U')
BEGIN
	CREATE TABLE Doctor (
		Id INT NOT NULL IDENTITY(1,1),
		Code VARCHAR(10) NOT NULL,
		FirstName VARCHAR(50) NOT NULL,
		LastName VARCHAR(50) NOT NULL,
		FieldId INT NOT NULL,
		CONSTRAINT PKDoctor PRIMARY KEY CLUSTERED (Id),
		CONSTRAINT UXDoctorCode UNIQUE (Code),
		CONSTRAINT FKFieldDoctorFieldId FOREIGN KEY (FieldId) REFERENCES Field (Id),
		INDEX IXDoctorLookup NONCLUSTERED (Code, FirstName, LastName, FieldId)
	)
END
GO

-- CREATE PATIENT
IF NOT EXISTS (SELECT * FROM  sys.sysobjects WHERE [name] = 'Patient' AND xtype = 'U')
BEGIN	
	CREATE TABLE Patient(
		Id INT NOT NULL IDENTITY(1,1),
		DocumentId VARCHAR(9)NOT NULL,
		FirstName VARCHAR(50) NOT NULL,
		LastName VARCHAR(50) NOT NULL,
		Tel VARCHAR(8) NOT NULL,
		Email VARCHAR (100)NOT NULL,
		CONSTRAINT PKPatient PRIMARY KEY CLUSTERED (Id),
		CONSTRAINT UXPatientDocumentId UNIQUE (DocumentId),
		CONSTRAINT UXPatientEmail UNIQUE (Email),
		INDEX IXPatientLookup NONCLUSTERED (DocumentId, FirstName, LastName, Tel, Email)
	)
END
GO

-- CREATE STATUS
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE [name] = 'Status' AND xtype = 'U')
BEGIN 
	CREATE TABLE [Status](
		Id INT NOT NULL,
		[Name] VARCHAR(50) NOT NULL,
		CONSTRAINT PKStatus PRIMARY KEY CLUSTERED (Id)
	)
END
GO			

-- CREATE APPOINTMENT
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE [name] = 'Appointment' AND xtype = 'U')
BEGIN
	CREATE TABLE Appointment(
		Id INT NOT NULL IDENTITY(1,1),
		[Date] DATETIME2 NOT NULL,
		PatientId INT NOT NULL,
		DoctorId INT NOT NULL,
		StatusId INT NOT NULL,
		CONSTRAINT PKAppointment PRIMARY KEY CLUSTERED (Id),
		CONSTRAINT FKPatientAppointmentPatientId FOREIGN KEY (PatientId) REFERENCES Patient (Id),
		CONSTRAINT FKDoctorAppointmentDoctorId FOREIGN KEY (DoctorId) REFERENCES Doctor (Id),
		CONSTRAINT FKStatusAppointmentStatusId FOREIGN KEY (StatusId) REFERENCES [Status] (Id),
		INDEX IXAppointmentLookup NONCLUSTERED ([Date], PatientId, DoctorId, StatusId)
	)
END
GO

-- CREATE ROLE
IF NOT EXISTS(SELECT * FROM sys.sysobjects WHERE [name] = 'Role' AND xtype = 'U')
BEGIN
	CREATE TABLE [Role](
		Id INT NOT NULL,
		[Name] NVARCHAR(50) NOT NULL,
		CONSTRAINT PKRole PRIMARY KEY CLUSTERED (Id),
	);
END

-- CREATE USER
IF NOT EXISTS(SELECT * FROM sys.sysobjects WHERE [name] = 'User' AND xtype = 'U')
BEGIN
	CREATE TABLE [User](
		Id INT NOT NULL IDENTITY(1, 1),
		Email VARCHAR(100) NOT NULL,
		[Password] BINARY(64) NOT NULL,
		PasswordSalt BINARY(64) NOT NULL,
		FirstName NVARCHAR(50) NOT NULL,
		LastName NVARCHAR(50) NOT NULL,
		RoleId INT NOT NULL,
		IsSuperAdmin BIT NOT NULL CONSTRAINT DFUserIsSuperAdmin DEFAULT 0,
		CONSTRAINT PKUser PRIMARY KEY CLUSTERED (Id),
		CONSTRAINT UXUserEmail UNIQUE NONCLUSTERED (Email),
		CONSTRAINT FKRoleUserRoleId FOREIGN KEY(RoleId) REFERENCES [Role](Id),
		INDEX IXUserLookup NONCLUSTERED (Email, FirstName, LastName, RoleId)
	);
END

-- CREATE SESSION
IF NOT EXISTS(SELECT * FROM sys.sysobjects WHERE [name] = 'Session' AND xtype = 'U')
BEGIN
	CREATE TABLE [Session](
		Id BIGINT NOT NULL IDENTITY(1,1),
		SessionId UNIQUEIDENTIFIER NOT NULL,
		UserId INT NOT NULL,
		DateIssued DATETIME2(7) NOT NULL,
		DateRefreshed DATETIME2(7) NULL,
		DateExpiry DATETIME2(7) NOT NULL,
		AddressIssued VARCHAR(40) NOT NULL,
		AddressRefreshed VARCHAR(40) NULL,
		RefreshToken BINARY(64) NOT NULL,
		CONSTRAINT PKSession PRIMARY KEY CLUSTERED (Id),
		CONSTRAINT UXSessionSessionId UNIQUE NONCLUSTERED (SessionId),
		CONSTRAINT FKUserSessionUserId FOREIGN KEY (UserId) REFERENCES [User](Id),
		INDEX IXSessionLookup NONCLUSTERED (AddressIssued, AddressRefreshed, DateIssued)
	);
END

--INSERT FIELD DATA
IF NOT EXISTS (SELECT * FROM Field WHERE Id = 1)
BEGIN 
	INSERT INTO Field (Id, Name) VALUES (1, 'Doctor General')
END

IF NOT EXISTS (SELECT * FROM Field WHERE Id = 2)
BEGIN 
	INSERT INTO Field (Id, Name) VALUES (2, 'Dentista')
END

IF NOT EXISTS (SELECT * FROM Field WHERE Id = 3)
BEGIN 
	INSERT INTO Field (Id, Name) VALUES (3, 'Pediatra')
END

IF NOT EXISTS (SELECT * FROM Field WHERE Id = 4)
BEGIN 
	INSERT INTO Field (Id, Name) VALUES (4, 'Cirujano')
END

-- INSERT STATUS DATA
IF NOT EXISTS (SELECT * FROM [Status] WHERE Id = 1)
BEGIN
	INSERT INTO [Status] (Id, [Name]) VALUES (1, 'Activa')
END

IF NOT EXISTS (SELECT * FROM [Status] WHERE Id = 2)
BEGIN
	INSERT INTO [Status] (Id, [Name]) VALUES (2, 'Cancelada')
END

-- INSERT ROLE DATA
IF NOT EXISTS(SELECT * FROM [Role] WHERE Id = 1)
BEGIN
	INSERT INTO [Role] (Id, [Name]) VALUES (1, 'Administrador');
END

IF NOT EXISTS(SELECT * FROM [Role] WHERE Id = 2)
BEGIN
	INSERT INTO [Role] (Id, [Name]) VALUES (2, 'Editor');
END

IF NOT EXISTS(SELECT * FROM [Role] WHERE Id = 3)
BEGIN
	INSERT INTO [Role] (Id, [Name]) VALUES (3, 'Asistente');
END